name: Backend CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: FindMyPatient
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_ROOT_USER: root
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306

    strategy:
      matrix:
        python-version: [3.10.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: backend

      - name: Apply database migrations
        run: |
          python manage.py makemigrations
          python manage.py migrate
        working-directory: backend

      - name: Run tests
        run: |
          python manage.py test
        working-directory: backend
