name: CD

on:
  workflow_run:
    workflows: ["Backend CI", "Frontend CI"]
    types:
      - completed

jobs:
  build-and-push-docker-image-to-docker-hub:
    if: ${{ github.event.workflow_run.conclusion == 'success'}}
    name: Build and Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Get .env file from secrets
        run: echo "${{ secrets.ENVIRONMENT_FILE }}" > .env

      - name: Make script executable
        run: chmod +x docker/build_and_push_image.sh

      - name: Run script
        run: ./build_and_push_image.sh ${{ secrets.DOCKER_HUB_USERNAME }}/findmypatient:${{ github.sha }} ${{ secrets.DOCKER_HUB_USERNAME }} ${{ secrets.DOCKER_HUB_PASSWORD }}
        working-directory: docker
